### ISSUE TITLE
multiple issues with the plugin

### ISSUE THREAD

**Issue by mkuts12** [taigaio/taiga-contrib-gitlab-auth#3]
Hey,

I tried using the dockerized version and had multiple errors:
- I had done what is written in the description, `virtualenv . && source bin/activate && pip install taiga...`  but when building the image I got an error that the module was not found on [this line](https://github.com/benhutchins/docker-taiga/blob/master/Dockerfile#L68). To overcome this issue I simply installed the package in the Dockerfile prior to this line.
- The project does not have any tags so the `svn export` did not work. I solved it by cloning the project and putting the relevant folder in place.
- after building the image, I tried to authenticate with gitlab but got an error that looked like "GITLAB_APP_ID is missing in the configuration". I had looked in the logs and added the variable in the local.py. The same happened with GITLAB_APP_SECRET. The Readme is misleading since it states that we should assign GITLAB_API_CLIENT_ID.
- Then I got an errer like "A string or byte object was expected". Looking at the stack trace I saw that the error was at the exprossion `authorized_redirect = re.sub(r'(?is)&code=.+', '', redirect_uri)`. I tried replacing it to `authorized_redirect = redirect_uri` but in vain. A new error arose. I don't have the stack but it will be provided if needed.
The redirectUri in the body of the request to `/api/v1/auth`  was `hot/login`. I don't understand that regex....

PLEASE help me fix it :\

**Comment by jespino** [comment]
Ok, I'm going to take a look to this problems. For your feedback.

**Comment by jespino** [comment]
Ok, sorry, somebody have developed another taiga-contrib-gitlab-auth plugin, and have registered in pypi (our plugin is based on taiga-contrib-github-auth and then, the README is the same).

We have developed it recently and isn't published in pypi yet, so the instructions doesn't work.

Tomorrow I will try to register and publish it in pypi and create the correct branch in github.

Thanks for your feedback!

**Comment by mkuts12** [comment]
ohhhh that explains so much! Thanks!

**Comment by jespino** [comment]
Finally, I've sent an email to the other taiga-contrib-github-auth plugin developers to take a decision. When they reply me I will write here the final decision.

**Comment by mkuts12** [comment]
Sorry for the delay, but thanks. While we are waiting I will try simply to replace the code in my local folder

**Comment by mkuts12** [comment]
ohh, I see you already updated the project. thank you!!!!!

**Comment by bameda** [comment]
:smiley_cat:
